### ISSUE TITLE
final configuration report

### ISSUE THREAD

**Issue by cavilacion** [zsusag/symbolic_semantics_of_probabilistic_programs#4]
It would be nice to have the tool spit out the data in this format, so it can be easily exported to other tools, such as LibreOffice Calc or the likes:
`Path \t sigma(x_0) \t ... \t sigma(x_{n-1}) \t k \t PC \t PO \t Pr(PC) \t Pr(PO) \n`
and then for each path a row with their respective data.
Note that I added the sampling index here: it is useful to have the maximum of all sample indices later.

**Comment by zsusag** [comment]
There are now two new flags you can provide to the tool: `--csv` and `-o <PATH>` or `--output <PATH>` as of commit: dedc460e40d94fd8750afafe15d8a168cc4753fd

- `--csv`: This will write the output in a CSV format, like you detailed above, but in a slightly different order (sigma is at the end instead of the front)
- `-o <PATH>` will redirect the output to a file referenced by `<PATH>`. If you don't provide the `--csv` flag, the previous "pretty" format will be written to the file.
